/**
 * This file was generated by kysely-generate.
 * Please do not edit it manually.
 */

import { ColumnType } from "kysely";

export enum Status {
  Confirmed = "CONFIRMED",
  Unconfirmed = "UNCONFIRMED",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Bacchus {
  bacchusId: Generated<number>;
  status: Status | null;
}

export interface DB {
  bacchi: Bacchus;
}
