/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface TestDbFooBar {
  confirmation_enum: "CONFIRMED" | "UNCONFIRMED";
  date: Date;
  date32: Date;
  datetime: Date;
  datetime64: Date;
  decimal: number;
  decimal128: number;
  decimal256: number;
  decimal32: number;
  decimal64: number;
  false: number;
  fixed_string: string;
  float32: number;
  float64: number;
  id: string;
  int128: number;
  int16: number;
  int256: number;
  int32: number;
  int64: number;
  int8: number;
  json: JsonObject;
  low_cardinality_string: string;
  nullable_string: string | null;
  string: string;
  string_array: string[];
  true: number;
  uint128: number;
  uint16: number;
  uint256: number;
  uint32: number;
  uint64: number;
  uint8: number;
}

export interface DB {
  "test_db.foo_bar": TestDbFooBar;
}
